waypoint_server:
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  position:
    x: 1
    y: 2
    z: 3
  scale: 1
  waypoints:
  - euler_angles:
      x: 2.8498978650661344e-06
      y: 5.468046064827092e-07
      z: -0.881539495464196
    id: registed_goal_3
    position:
      x: -0.3334076404571533
      y: 7.904827117919922
      z: -3
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: 5.456479470932398e-06
      y: -2.817918402842068e-06
      z: 1.2554299994138314
    id: registed_goal_3
    position:
      x: -0.24599742889404297
      y: 21.527488708496094
      z: -3
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: 2.1350320486053817e-06
      y: -2.0173539903023396e-06
      z: 1.428877641408696
    id: registed_goal_2
    position:
      x: 0.09689760208129883
      y: 28.83531951904297
      z: -3
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: 0.0
      y: 0.0
      z: 3.1245927460524645
    id: registed_goal_1
    position:
      x: -9.554281234741211
      y: 29.224092483520508
      z: -3
    properties:
      goal_radius: 1.5
  - euler_angles:
      x: 1.1533996147562065e-07
      y: -8.925952998950493e-08
      z: 2.8654792446924304
    id: registed_goal_4
    position:
      x: -9.68386459350586
      y: 23.042373657226562
      z: -3
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: 1.1533996147562065e-07
      y: -8.925952998950493e-08
      z: 2.8654792446924304
    id: registed_goal_4
    position:
      x: -9.932964324951172
      y: 7.915388584136963
      z: -3
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: -8.597044274981507e-08
      y: -3.6642234357842085e-08
      z: 2.199528753806452
    id: registed_goal_0
    position:
      x: -10.344225883483887
      y: -4.486055374145508
      z: -3
    properties:
      goal_radius: 1.5
  - connections:
    - 2
    euler_angles:
      x: 7.227359485514843e-08
      y: 2.1144105000203695e-07
      z: -0.8815394954649673
    id: 1
    position:
      x: -0.22384357452392578
      y: -4.401132583618164
      z: 0
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - connections:
    - 1
    euler_angles:
      x: 0.0
      y: 0.0
      z: 0.04275799298787434
    id: 3
    position:
      x: -0.34309864044189453
      y: 7.774312496185303
      z: 6
    properties:
      goal_radius: 1.5
  - euler_angles:
      x: 1.7788611839630653e-07
      y: -2.5919307766741895e-07
      z: -0.15346629730566846
    id: 2
    position:
      x: -9.95081901550293
      y: 7.105714321136475
      z: 1
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: -2.8333930893600277e-07
      y: -1.3617400118626222e-07
      z: -2.9881263562841287
    id: 2
    position:
      x: -10.255844116210938
      y: -3.308350086212158
      z: 1
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: 1.7788611839630653e-07
      y: -2.5919307766741895e-07
      z: -0.15346629730566846
    id: 2
    position:
      x: 0.3827230930328369
      y: -3.7182517051696777
      z: 1
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: -2.8333930893600277e-07
      y: -1.3617400118626222e-07
      z: -2.9881263562841287
    id: 2
    position:
      x: 0.5020862817764282
      y: 28.41087532043457
      z: 1
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
  - euler_angles:
      x: 1.7788611839630653e-07
      y: -2.5919307766741895e-07
      z: -0.15346629730566846
    id: 2
    position:
      x: -9.33707332611084
      y: 29.83411979675293
      z: 1
    properties:
      Stop_wp: Stop_OFF
      goal_radius: 1.5
